services:
  - type: web
    name: arposhop
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
